title: Ke LUO
url: "https://github.com/Ken-Leo"
baseurl: "/kenleo.resume"

markdown: kramdown
#ins_logo: " "

tracking_id: #

footer: yes
footer_url: "https://github.com/Ken-Leo"
footer_text: "Page updated by Ken"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/kenleo.resume/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
